{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# \"Supplemental\" Functions\n",
    "\n",
    "def get_supp_county_population(state, county = '',verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns historical county population data\n",
    "\n",
    "        >>>get_supp_county_population('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'county_population?'\n",
    "    add_state = 'state=' + state\n",
    "    add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_county + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        county_population_df = json_normalize(requests.get(full_url).json())\n",
    "        return county_population_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)\n",
    "        \n",
    "def get_supp_not_pharmacies(key = 'WaPo', verification = True):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns list of 330+ BUYER_DEA_NOs that we've identified as mail order or hospitals and not retail or chain pharmacies)\n",
    "\n",
    "        >>>get_supp_not_pharmacies('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'not_pharmacies?'\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        not_pharmacies_df = json_normalize(requests.get(full_url).json())\n",
    "        return not_pharmacies_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)\n",
    "        \n",
    "def get_supp_state_population(state, verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation) bool, str) -> pd.df\n",
    "        Returns historical state population data\n",
    "\n",
    "        >>>get_supp_state_population('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'state_population?'\n",
    "    add_state = 'state=' + state\n",
    "    #add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        state_population_df = json_normalize(requests.get(full_url).json())\n",
    "        return state_population_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL and state are correct: ', full_url)\n",
    "        \n",
    "def get_supp_pharmacy_latlon(state, county = '',verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns pharmacy latitude and longitude data by Buyer_DEA_Number\n",
    "\n",
    "        >>>get_supp_pharmacy_latlon('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'pharmacy_latlon?'\n",
    "    add_state = 'state=' + state\n",
    "    add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_county + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        pharmacy_latlon_df = json_normalize(requests.get(full_url).json())\n",
    "        return pharmacy_latlon_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)\n",
    "        \n",
    "def get_supp_pharmacy_counties(state, county = '',verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns each pharmacy's county FIPS id number by Buyer DEA Number\n",
    "\n",
    "        >>>get_supp_pharmacy_counties('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'pharmacy_counties?'\n",
    "    add_state = 'state=' + state\n",
    "    add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_county + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        pharmacy_counties_df = json_normalize(requests.get(full_url).json())\n",
    "        return pharmacy_counties_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)\n",
    "        \n",
    "def get_supp_pharmacy_tracts(state, county = '',verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns each pharmacy's census tract FIPS code\n",
    "\n",
    "        >>>get_supp_pharmacy_tracts('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'pharmacy_tracts?'\n",
    "    add_state = 'state=' + state\n",
    "    add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_county + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        pharmacy_tracts_df = json_normalize(requests.get(full_url).json())\n",
    "        return pharmacy_tracts_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)\n",
    "        \n",
    "def get_supp_pharmacy_cbsa(state, county = '',verification = True, key = 'WaPo'):\n",
    "    '''(str(two letter abbreviation), bool, str, str) -> pd.df\n",
    "        Returns pharmacy core-based statistical area FIPS code\n",
    "\n",
    "        >>>get_supp_pharmacy_cbsa('OH', 'Summit')\n",
    "            EXAMPLE OUTPUT\n",
    "    '''\n",
    "\n",
    "    base_url = 'https://arcos-api.ext.nile.works/v1/'\n",
    "    function_url = 'pharmacy_cbsa?'\n",
    "    add_state = 'state=' + state\n",
    "    add_county = '&county=' + county\n",
    "    add_key = '&key=' + key\n",
    "    full_url = base_url + function_url + add_state + add_county + add_key\n",
    "\n",
    "    if verification == True:\n",
    "        print(full_url)\n",
    "        pharmacy_cbsa_df = json_normalize(requests.get(full_url).json())\n",
    "        return pharmacy_cbsa_df\n",
    "    else:\n",
    "        print('Problem encountered, not returning data:')\n",
    "        print('Either verification == False')\n",
    "        print('Or problem with API encountered, please verify URL, state and county are correct: ', full_url)        "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
